apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "geth-helm.fullname" . }}
  labels:
    app: {{ template "geth-helm.name" . }}
    chart: {{ template "geth-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "geth-helm.fullname" . }}
  replicas: {{ .Values.geth.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "geth-helm.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "geth-helm.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: geth
        image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
        resources:
          requests:
            memory: "8000Mi"
          limits:
            memory: "8500Mi"
        imagePullPolicy: {{ .Values.geth.imagePullPolicy }}
        command: ["geth --goerli"]
        args:
        - --http
        - --http.corsdomain=*
        - --http.vhosts=*
        - --http.addr=0.0.0.0
        - --cache=1024
        ports:
        - name: rpc
          containerPort: 8545
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "geth-helm.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      storageClassName: {{ .Values.geth.storageClass }}
      accessModes:
        - "ReadWriteMany"
      resources:
          requests:
            storage: "500Gi"
